/**
 * @privapilot/protocol - Payload Contracts and Type Boundaries
 *
 * Enforces compile-time and runtime guarantees:
 * RawCapture -> DetectionReport -> SanitizedContext -> NetworkPayload
 * RawCapture CANNOT be passed to Network clients.
 */

import { ScreenshotPixelBox, ViewportCssPixelBox, ViewportMetadata } from './coordinates.js';
import { SceneGraph, SceneGraphElement } from './scene-graph.js';

export type SensitiveCategory =
  | 'password'
  | 'email'
  | 'phone'
  | 'credit_card'
  | 'cvv'
  | 'bank_account'
  | 'national_id'
  | 'date_of_birth'
  | 'address'
  | 'username'
  | 'auth_code'
  | 'token'
  | 'face'
  | 'high_risk_surface'
  | 'uninspectable';

export type RedactionMethod = 'opaque_mask' | 'gaussian_blur';

export interface SensitiveRegion {
  readonly id: string;
  readonly category: SensitiveCategory;
  readonly viewportBox: ViewportCssPixelBox;
  readonly screenshotBox: ScreenshotPixelBox;
  readonly detectorSource: 'dom_semantic' | 'text_pii_regex' | 'face_model' | 'surface_detector' | 'user_override';
  readonly method: RedactionMethod;
  readonly label?: string;
}

/**
 * Raw capture produced on the local client. Strictly internal.
 */
export interface RawCapture {
  readonly _brand: 'RawCapture_InternalOnly';
  readonly captureId: string;
  readonly timestamp: number;
  readonly rawScreenshotDataUrl: string;
  readonly rawDomSummary: any;
  readonly metadata: ViewportMetadata;
}

/**
 * Intermediate report from in-browser detectors.
 */
export interface DetectionReport {
  readonly captureId: string;
  readonly timestamp: number;
  readonly regions: ReadonlyArray<SensitiveRegion>;
  readonly uninspectableSurfacesFound: boolean;
  readonly requiresFailClosedBlock: boolean;
  readonly failClosedReason?: string;
}

export type ElementRole =
  | 'button'
  | 'link'
  | 'input'
  | 'select'
  | 'textarea'
  | 'checkbox'
  | 'radio'
  | 'menuitem'
  | 'tab'
  | 'heading'
  | 'generic';

export type ActionCapability = 'click' | 'type' | 'select' | 'scroll';

export interface SanitizedElement {
  readonly localId: string; // e.g. "el_1", "el_2"
  readonly role: ElementRole;
  readonly sanitizedName: string;
  /** Coarse normalized bounds: [normX, normY, normW, normH] between 0 and 1 */
  readonly coarseBounds: readonly [number, number, number, number];
  readonly state: ReadonlyArray<'enabled' | 'disabled' | 'visible' | 'checked' | 'focused'>;
  readonly actionCapabilities: ReadonlyArray<ActionCapability>;
}

export interface SanitizedPageState {
  readonly title: string;
  readonly viewport: readonly [number, number];
}

/**
 * Sanitized context produced by local redaction pipeline. Safe to pass to Network client.
 */
export interface SanitizedContext {
  readonly _brand: 'SanitizedContext_Verified';
  readonly protocolVersion: '1.0';
  readonly runId: string;
  readonly captureId: string;
  readonly goal: string;
  /** Base64 encoded sanitized image with opaque masks and face blurs applied */
  readonly sanitizedScreenshotDataUrl: string;
  readonly elements: ReadonlyArray<SanitizedElement>;
  readonly pageState: SanitizedPageState;
  readonly maskCount: number;
  /**
   * What the on-device Vision Transformer read on surfaces the DOM cannot describe.
   *
   * Empty on an ordinary page: the ViT is spent only where the DOM is blind, because
   * each region costs a full forward pass. `label: null` means the model declined to
   * commit - see MIN_CLASSIFICATION_MARGIN.
   */
  readonly visionObservations: ReadonlyArray<{
    readonly surfaceId: string;
    readonly regionId: string;
    readonly label: string | null;
    readonly bestLabel: string;
    readonly margin: number;
    readonly confident: boolean;
    readonly box: readonly [number, number, number, number];
  }>;
  /** How the ViT behaved this capture, reported rather than assumed. */
  readonly visionTelemetry: {
    readonly modelFamily: string;
    readonly providerUsed: string;
    readonly regionsProposed: number;
    readonly regionsEmbedded: number;
    readonly totalInferenceMs: number;
    readonly available: boolean;
    readonly error?: string;
  };
  /** Redaction scheme this payload was produced under. */
  readonly redactionManifest: import('./redaction.js').RedactionManifest;
  /** Full multimodal SceneGraph generated by fused DOM and Vision lanes */
  readonly sceneGraph?: SceneGraph;
  readonly payloadDigestSha256: string;
  readonly timestamp: number;
}

/**
 * Closed Network Payload schema sent over the wire to Centralized Reasoning Server.
 *
 * Privacy Invariants:
 * - `SceneGraphConflict` is NEVER serialized here (it remains strictly on the client).
 * - Only opaque refs and PII-screened elements are transmitted.
 */
export interface SanitizedNetworkPayload {
  readonly protocolVersion: '1.0';
  readonly runId: string;
  readonly goal: string;
  readonly screenshot: string; // Base64 data URL
  readonly elements: ReadonlyArray<SanitizedElement>;
  readonly pageState: SanitizedPageState;
  /** Optional multimodal scene graph elements (strictly opaque refs, zero client-internal conflicts) */
  readonly sceneGraphElements?: ReadonlyArray<SceneGraphElement>;
  /**
   * The redaction scheme this payload was produced under. The problem statement
   * requires the server to be aware of it; without this the server was reasoning
   * over holes it had no description of.
   */
  readonly redactionManifest: import('./redaction.js').RedactionManifest;
  /**
   * What this run has already done, in sanitized terms.
   *
   * Without it the server reasons about every step as if it were the first: on a
   * multi-step task it re-proposed the click it had just made, because the goal
   * still named that control and nothing told it the page had already responded.
   * Labels here are the same sanitized names already present in `elements`, so this
   * discloses nothing new.
   */
  readonly recentActions?: ReadonlyArray<{
    readonly kind: string;
    readonly targetLabel?: string;
  }>;
}

/**
 * Converts a SceneGraphElement to a SanitizedElement for backward compatibility with legacy consumers.
 */
export function sceneGraphElementToSanitizedElement(sgEl: SceneGraphElement): SanitizedElement {
  let role: ElementRole = 'generic';
  const r = sgEl.role.toLowerCase();
  if (r === 'button') role = 'button';
  else if (r === 'link') role = 'link';
  else if (r === 'input' || r === 'text_input') role = 'input';
  else if (r === 'select') role = 'select';
  else if (r === 'textarea') role = 'textarea';
  else if (r === 'checkbox' || r === 'checkbox_or_toggle') role = 'checkbox';
  else if (r === 'radio') role = 'radio';

  const caps: ActionCapability[] = [];
  for (const a of sgEl.affordances) {
    if (a === 'clickable' || a === 'click') caps.push('click');
    if (a === 'typable' || a === 'type') caps.push('type');
    if (a === 'selectable' || a === 'select') caps.push('select');
    if (a === 'scrollable' || a === 'scroll') caps.push('scroll');
  }
  if (caps.length === 0) caps.push('click');

  return {
    localId: sgEl.ref,
    role,
    sanitizedName: sgEl.labelHint || sgEl.role,
    coarseBounds: sgEl.bbox,
    state: ['visible', 'enabled'],
    actionCapabilities: caps
  };
}

/**
 * Strict Network Boundary Transform: converts a client-internal SanitizedContext
 * into a closed SanitizedNetworkPayload safe to cross the network wire.
 *
 * Privacy Invariants:
 * - Omits all internal diagnostic claims, raw dom summaries, and SceneGraphConflict records.
 * - Extracts only opaque-ref SceneGraphElements with screened labelHints.
 */
export function sanitizeContextForNetwork(
  sanitized: SanitizedContext,
  recentActions?: ReadonlyArray<{ kind: string; targetLabel?: string }>
): SanitizedNetworkPayload {
  return {
    protocolVersion: sanitized.protocolVersion || '1.0',
    runId: sanitized.runId || 'run_default',
    goal: sanitized.goal || '',
    screenshot: sanitized.sanitizedScreenshotDataUrl || '',
    elements: sanitized.elements || [],
    pageState: sanitized.pageState || { title: '', viewport: [1280, 720] },
    redactionManifest: sanitized.redactionManifest,
    ...(sanitized.sceneGraph ? { sceneGraphElements: sanitized.sceneGraph.elements } : {}),
    ...(recentActions && recentActions.length ? { recentActions } : {})
  };
}

/**
 * Closed Page-Aware Chat Payload schema. Derived strictly from SanitizedContext.
 */
export interface SanitizedChatPayload {
  readonly _brand: 'SanitizedChatPayload_Verified';
  readonly protocolVersion: '1.0';
  readonly message: string;
  readonly elements: ReadonlyArray<SanitizedElement>;
  readonly sanitizedTitle: string;
  readonly maskCount: number;
}

/**
 * Contextless General Chat Payload schema. Zero browser/page state.
 */
export interface GeneralChatPayload {
  readonly protocolVersion: '1.0';
  readonly message: string;
}

